'use strict';

export default {
    FETCH_BUILD_INFO: 'FETCH_BUILD_INFO',
    FETCH_BUILD_INFO_REJECTED: 'FETCH_BUILD_INFO_REJECTED',
    FETCH_BUILD_INFO_FULFILLED: 'FETCH_BUILD_INFO_FULFILLED',
    GET_SENSOR_DATA: 'GET_SENSOR_DATA',
    GET_SENSOR_DATA_SUCCESS: 'GET_SENSOR_DATA_SUCCESS',
    GET_SENSOR_DATA_FAIL: 'GET_SENSOR_DATA_FAIL',
    GET_USAGE_DATA: 'GET_USAGE_DATA',
    GET_USAGE_DATA_SUCCESS: 'GET_USAGE_DATA_SUCCESS',
    GET_USAGE_DATA_FAIL: 'GET_USAGE_DATA_FAIL'
};